FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
         build-essential \
         cmake \
         g++ \
         libeigen3-dev \
         clang-format \
         git \
   && rm -rf /var/lib/apt/lists/*
